name: Question-Answer based RAG System 

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest 

        env:
            GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

        steps:
          - name: checkout repository 
            uses: actions/checkout@v3

          - name: set up python environment
            uses: actions/setup-python@v4 
            with:
                python-version: "3.13.2" 

          - name: Install dependencies 
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt 

          - name: Check python syntax 
            run: | 
              python -m compileall


    docker_build:
        name: Build Docker Image 
        runs-on: ubuntu-latest 
        needs: build 

        steps:
          - name: Checkout
            uses: actions/checkout@v3 

          - name: log in to DockerHub 
            run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          - name: Build Docker Image 
            run: | 
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rag-app 

          - name: Push Docker Image to Hub 
            run: | 
              docker push ${{secrets.DOCKERHUB_USERNAME}}/rag-app